import pandas as pd
import pandas_ta as ta

def add_features(df):
    """
    Add technical indicators and other features to the dataframe.
    """
    if df is None or df.empty:
        return None
    
    df = df.copy()
    
    # Ensure date is datetime and set as index
    if 'date' in df.columns:
        df['date'] = pd.to_datetime(df['date'])
        df.set_index('date', inplace=True)
    
    # RSI
    df['rsi'] = ta.rsi(df['close'], length=14)
    
    # MACD
    macd = ta.macd(df['close'])
    df = pd.concat([df, macd], axis=1)
    
    # Bollinger Bands
    bbands = ta.bbands(df['close'])
    df = pd.concat([df, bbands], axis=1)
    
    # ATR
    df['atr'] = ta.atr(df['high'], df['low'], df['close'])
    
    # Simple Moving Averages
    df['sma_20'] = ta.sma(df['close'], length=20)
    df['sma_50'] = ta.sma(df['close'], length=50)
    df['sma_200'] = ta.sma(df['close'], length=200)
    
    # Returns
    df['return_1d'] = df['close'].pct_change()
    df['return_5d'] = df['close'].pct_change(5)
    
    # Volatility
    df['volatility_20'] = df['return_1d'].rolling(window=20).std()
    
    # Target: Next day direction (1 for Up, 0 for Down)
    df['target_return'] = df['close'].shift(-1)
    df['target_dir'] = (df['target_return'] > df['close']).astype(int)
    
    # Drop NaN values generated by indicators
    df.dropna(inplace=True)
    
    return df
